### PR TITLE
Removed exception during Product Save, improved performance [Fix #121]

### LINKED ISSUE #121: ReverbSync generates exception, warning message when saving a Product for which Sync to Reverb = No
When a product with Sync to Reverb = No is saved the user is shown an error/warning which states: 

> The "Sync to Reverb" value for this product has been set to "No"; this product can not be synced to Reverb as a result

This may be informational, but is not a standard Magento practice.

Internally this is the result of the product save event triggering an attempt to sync the product; this results in an exception being thrown from `Reverb_ReverbSync_Helper_Sync_Product::executeIndividualProductDataSync()`.  This method will require the product to be loaded an additional time, and could have significant performance and resource ramifications during bulk imports.  The event should use an early-exit rather than attempting a sync.

### PR DESCRIPTION
**Pull request by StevenWolfe**
Product Save event handler now explicitly checks the value of the "Sync to Reverb" attribute and exits early.  This isn't ideal, as it generates one SQL query per product save event, however it should avoid a fair number of `$product->load()` calls which are currently a waste for products which are not sync'd to Reverb.

The proper fix would be to either ensure the Sync to Reverb attribute has been loaded on the product being saved (so that no extra queries are required) or to queue the product ID's for async batch processing.

### CODE REVIEW

**Comment by skwp** [comment]
@dunagan5887 can you please give this a once over?

**Comment by StevenWolfe** [comment]
I've got a couple more tweaks to this to help avoid some of the SQL queries

**Comment by StevenWolfe** [comment]
All set for the moment; this will load the `rev_sync` product attribute if needed.  It still has room for improvement as any sync will require an explicit product load (regardless of whether the product has already been fully loaded prior to the event being thrown).

File: app/code/community/Reverb/ReverbSync/Model/Observer.php [hunk 1]
```diff
@@ -7,11 +7,24 @@ class Reverb_ReverbSync_Model_Observer
...
-            $listingWrapper = $productSyncHelper->executeIndividualProductDataSync($product_id);
+      try
+      {
+          $product = $observer->getProduct();
+          $product_id = $product->getId();
+
+          $syncToReverb = $product->getData('rev_sync');
+          if (is_null($syncToReverb)) {
+              // TODO: This will potentially generate one SQL query per product saved.  Revamp this to queue the check and process in async batches.
+              $syncToReverb = Mage::getResourceModel('catalog/product')->getAttributeRawValue($product_id, 'rev_sync');
```
Comment (skwp) [inline app/code/community/Reverb/ReverbSync/Model/Observer.php]: curious..why would this atttribute have to be re-fetched?  dont' we have it from getting the product in the observer?

**Comment by StevenWolfe** [comment]
There's a couple things here.  The first is that this event will fire during any `product->save()` call, which can be done on partially loaded products.  The `$product->getData('rev_sync')` call is  way to see if the attribute has been loaded on the product or not.

The other part of it is that the extension is currently passing around the Product ID rather than the loaded Product instance.  You can see that this event handler calls:

    $listingWrapper = $productSyncHelper->executeIndividualProductDataSync($product_id);

Which will only pass the product ID, requiring the product to be loaded again (regardless of whether or not it already has been).

Fixing that is likely larger than I can tackle for MSL, but I'd suggest trying to keep `.load()` calls to a minimum and working with collections rather than individual instances--the gains should be significant.

File: app/code/community/Reverb/ReverbSync/Model/Observer.php (hunk 1 above)
Comment (StevenWolfe) [inline app/code/community/Reverb/ReverbSync/Model/Observer.php]: There's a couple things here. The first is that this event will fire during any product->save() call, which can be done on partially loaded products. The $product->getData('rev_sync') call is way to see if the attribute has been loaded on the product or not.

The other part of it is that the extension is currently passing around the Product ID rather than the loaded Product instance. You can see that this event handler calls:

$listingWrapper = $productSyncHelper->executeIndividualProductDataSync($product_id);

Which will only pass the product ID, requiring the product to be loaded again (regardless of whether or not it already has been).

Fixing that is likely larger than I can tackle for MSL, but I'd suggest trying to keep .load() calls to a minimum and working with collections rather than individual instances--the gains should be significant.

Comment (StevenWolfe) [inline app/code/community/Reverb/ReverbSync/Model/Observer.php]: that response was a bit broader than your question :)

In a nutshell there's no guarantee that `$observer->getProduct()` will return a fully-loaded product.  Magento typically loads only explicitly requested attributes.  It's a trade-off of the 4NF schema of Magento's DB--extreme flexibility, horror-show joins.

Comment (dunagan5887) [inline app/code/community/Reverb/ReverbSync/Model/Observer.php]: This is true, often-times a product will be loaded with only a subset of its attributes; as such we can not always rely on the product having been fully loaded with the rev_sync attribute at this point.

Steven's call to getAttributeRawValue() selects the rev_sync value for the product with an adapter query, avoiding a number of ORM related event-observers which likely are unnecessary in terms of loading the rev_sync attribute. 

By returning false (as opposed to throwing a Reverb_ReverbSync_Model_Exception_Product_Excluded exception) is that no messaging will be shown to the admin that the product was not synced due to this setting. This is a business level decision on whether or not to assume the admin user knows of that setting and knows that the product isn't being synced.

Comment (skwp) [inline app/code/community/Reverb/ReverbSync/Model/Observer.php]: I think on the business level I'm in agreement that we should not throw warnings here. People turning off reverb sync are doing that on purpose. So if you guys both agree this is the right technical thing to do I'm good to merge.

Comment (dunagan5887) [inline app/code/community/Reverb/ReverbSync/Model/Observer.php]: Technically it's definitely an improvement, especially for instances which have a majority of products set not to sync
